# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Heroku Docker registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login

    - name: Build and Push IdentityServer Docker Image
      env:
        HEROKU_APP_NAME: gibbon-api-auth
        ConnectionStrings__DefaultConnection: ${{ secrets.CONNECTIONSTRINGS__DEFAULTCONNECTION }}
        AUTHAUTHORITY: ${{ env.AUTHAUTHORITY }}
        ALLOWEDORIGINS: ${{ env.ALLOWEDORIGINS }}
      run: |
        docker build -t registry.heroku.com/${HEROKU_APP_NAME}/web -f IdentityServer/Dockerfile \
          --build-arg ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection} \
          --build-arg AuthAuthority=${AUTHAUTHORITY} \
          --build-arg AllowedOrigins=${ALLOWEDORIGINS} \
          .
        docker push registry.heroku.com/${HEROKU_APP_NAME}/web

    - name: Build and Push Host Docker Image
      env:
        HEROKU_APP_NAME: gibbon-api
        ConnectionStrings__DefaultConnection: ${{ secrets.CONNECTIONSTRINGS__DEFAULTCONNECTION }}
        AUTHAUTHORITY: ${{ env.AUTHAUTHORITY }}
        ALLOWEDORIGINS: ${{ env.ALLOWEDORIGINS }}
      run: |
        docker build -t registry.heroku.com/${HEROKU_APP_NAME}/web -f Host/Dockerfile \
          --build-arg ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}  \
          --build-arg AuthAuthority=${AUTHAUTHORITY} \
          --build-arg AllowedOrigins=${ALLOWEDORIGINS} \
          .
        docker push registry.heroku.com/${HEROKU_APP_NAME}/web

    - name: Release IdentityServer Docker Image
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: gibbon-api-auth
      run: heroku container:release web --app ${HEROKU_APP_NAME}

    - name: Release Host Docker Image
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: gibbon-api
      run: heroku container:release web --app ${HEROKU_APP_NAME}
